Fix for asset procompilation with Rails5/Sprockets3: "NoMethodError: undefined method `find_asset' for nil:NilClass ." Error happens when config.assets.compile = false is configured because Rails.application.assets is not set anymore in that case. Fix should be good to close issue no. 9: https://github.com/franzheidl/sass-inline-svg/issues/9